### PR TITLE
Allow installation on PHP 7.2

### PR DESCRIPTION
**Pull request by davidwindell**
Now that Magento 2.2.8 and 2.3.1 have been released with official support for PHP 7.2

### CODE REVIEW

**Comment by cjnewbs** [comment]
@mattgarde-pca Would you be able to bump the version number in `composer.json` and create a new release so that packagist will pick the changes up. I would be very grateful.

**Comment by ghost** [comment]
@cjnewbs I've just incremented the version now. We have the old github services app installed. I just need to change that to the new webooks but I'll have this updated soon.

**Comment by ghost** [comment]
@cjnewbs version 2.0.8 is now the latest.

**Comment by cjnewbs** [comment]
@mattgarde-pca Awesome! Thanks for that. Looking in the issues tab https://github.com/PCAPredict/magento2/issues/27 can probably be set to resolved now as well. Have a great day!

**Pull request merged**
